### ISSUE TITLE
Widgets?

### ISSUE THREAD

**Issue by iamtravjohnson** [puikinsh/ElaAdmin#1]
The "Widgets" link doesn't work, brings you to a 404 page. The "widget.html" file appears to not exist in the zip file. Any plans on including it in a future update?

**Comment by puikinsh** [comment]
Dude, there are like millions of pages already and this template is completely free. And yet, it is still not enough for you :) 
How about contributing and making some extra widgets?

**Comment by iamtravjohnson** [comment]
Why the rude comment? Definitely no need to be a smart ass. I was simply informing you that the 'Widgets' link didn't work in case it was an oversight on your behalf that you would possibly want to fix. That's what fellow devs do, at least the appreciative ones that I've dealt with over the past 10+ years.

Also, free or not, it seems a little strange to go through the effort that you did to produce this awesome dashboard template and put out something that has broken links in it.

Get rid of the 'Widgets' link in the sidebar if it serves no purpose ✌🏼
