### ISSUE TITLE
dropzone.js returns 405 on uploading a file

### ISSUE THREAD

**Issue by chaitanyabhardwaj** [puikinsh/ElaAdmin#17]
https://colorlib.com/polygon/elaadmin/form-dropzone.html
Drag 'n' drop uploading of file using dropzone.js returns
POST https://colorlib.com/polygon/elaadmin/form-dropzone.html 405 ()

**Comment by puikinsh** [comment]
Do you know what 405 error stands for? It means Method Not Allowed. We don't allow to upload any files on our demo site for obvious reasons.
