### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by faljse** [puikinsh/ElaAdmin#2]
Hi, got a question regarding licensing:
Do you require notice of author visible on every page, or is it fine to put it in the source code and/or an about box?

**Comment by puikinsh** [comment]
Would appreciate the 1st option but also the 2nd option will work.

**Comment by jboilesen** [comment]
@puikinsh  please, add your license to source. I think that if you agree with 1st and 2nd option, you would like to use a MIT License ;)
