### ISSUE TITLE
Tag <a> styles isn't working with "btn" classes

### ISSUE THREAD

**Issue by ronanflavio** [puikinsh/ElaAdmin#24]
If I try using `<button>` tag, as showing in docs, the buttons style is ok:
```
<button type="button" class="btn btn-primary">Primary</button>
```
But if I try using `<a>` tag, the style is not applied to the button:
```
<a href="#" class="btn btn-primary">Primary</a>
```

**Comment by ronanflavio** [comment]
Please, visit this page:
https://colorlib.com/polygon/elaadmin/ui-button.html
Inspect any button and change de the tag `<button>` to `<a>` and see what happens.

**Comment by ronanflavio** [comment]
Hmm. I see...
It's only with the `btn-default`.
The outer collor disappears.
Take a look:
![captura de tela de 2018-05-24 10-41-50](https://user-images.githubusercontent.com/8162211/40489288-268f3cb2-5f3f-11e8-9e80-610966975bc8.png)

**Comment by puikinsh** [comment]
It is just styled like that to begin with. See default button styling with <button> tag as well.

**Comment by ronanflavio** [comment]
Thanks bro.
I made my own `btn-default` style to be applied at the `<a>` tag.
