### ISSUE TITLE
An awesome Bootstrap 4 template.. Will you be developing it further?

### ISSUE THREAD

**Issue by sunitk** [puikinsh/ElaAdmin#30]
### Subject of the issue
I love this template as it has the layout facility like that of some Bootstrap 3 templates (Metis template) and its clean. I would love to eventually buy a license for this template. So awaiting further development. So many templates out there are not at all great yet they charge money for it. Your template is one that I would gladly pay for.

**Comment by puikinsh** [comment]
We have no plans for new features at this point but it will be maintained for many years to come.

**Comment by sunitk** [comment]
ElaAdmin has fixed header fixed sidebar feature which sets it apart from
other commercial templates.

I wish I was a CSS expert as I would have gladly contributed.

Sorry to hear that it won't be developed further.

**Comment by puikinsh** [comment]
I'm not saying that it won't be ever. We just don't have an exact roadmap in place since there haven't been any feature request. It is already awesome as it is.
